### ISSUE TITLE
Project is crashing in higher version (Android Oreo)

### ISSUE THREAD

**Issue by NirmalPrajapat** [himangipatel/ImagePickerUtil#1]
Application is getting crashed in higher version i.e Android Oreo while image selection from gallery.
I have also added provider in manifest file.

`<provider android:name="android.support.v4.content.FileProvider" android:authorities="com.imagepicker" android:exported="false" android:grantUriPermissions="true"> <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/provider_paths" /> </provider>`

**Comment by himangipatel** [comment]
update your gradle version to 0.1.2

**Comment by NirmalPrajapat** [comment]
Thanks, but that issue was from my end.:)
